ARG time_zone
ARG NODE_VERSION=22.20.0
ARG PNPM_VERSION=10.18.2

FROM node:${NODE_VERSION}-slim

ENV TZ=${time_zone}

WORKDIR /frontend

RUN npm install -g pnpm@${PNPM_VERSION}

COPY . /frontend

RUN pnpm install

# RUN npx nuxi upgrade --force

EXPOSE 3030
EXPOSE 24678

CMD ["pnpm", "dev"]
