ARG tz
ARG NODE_VERSION=22.20.0
ARG PNPM_VERSION=10.17.1

FROM node:${NODE_VERSION}-slim

ENV TZ=${tz}

WORKDIR /frontend

RUN npm install -g pnpm@${PNPM_VERSION}

COPY . /frontend

RUN pnpm install

# RUN npx nuxi upgrade --force

EXPOSE 3030
EXPOSE 24678

CMD ["pnpm", "dev"]