allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@vesperjs/nuxt@0.9.5'
  - '@vesperjs/shared@0.9.5'
  - '@vue/test-utils@2.4.11'
overrides:
  '@typescript-eslint/typescript-estree': ^8.60.1
  '@vue/compiler-core': ^3.6.0-beta.13
  '@vue/compiler-dom': ^3.6.0-beta.13
  '@vue/compiler-sfc': ^3.6.0-beta.13
  '@vue/reactivity': ^3.6.0-beta.13
  '@vue/runtime-core': ^3.6.0-beta.13
  '@vue/runtime-dom': ^3.6.0-beta.13
  '@vue/shared': ^3.6.0-beta.13
  eslint: ^10.4.1
  vite: ^8.0.16
  vitest: ^4.1.8
  vue: ^3.6.0-beta.13
