allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - daisyui@5.7.37
  - lucide-static@1.45.0
overrides:
  '@vue/compiler-core': ^3.6.0-rc.8
  '@vue/compiler-dom': ^3.6.0-rc.8
  '@vue/compiler-sfc': ^3.6.0-rc.8
  '@vue/reactivity': ^3.6.0-rc.8
  '@vue/runtime-core': ^3.6.0-rc.8
  '@vue/runtime-dom': ^3.6.0-rc.8
  '@vue/shared': ^3.6.0-rc.8
  vue: ^3.6.0-rc.8
